import React from "react";
import Star from "./Star";

const StarryBackground = () => {
  return (
    <>
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
      <Star />
    </>
  );
};

export default StarryBackground;
